
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("product/new", "Create product")) ?>
</div>

<?php echo $this->tag->form(array("product/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search product</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("name", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price">Price</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("price", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
